---
- name: add java repository
  apt_repository:
    repo: "ppa:webupd8team/java"

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# https://coderwall.com/p/zzdapg/ansible-recipe-to-install-java-7-selecting-the-oracle-license
- name: accept oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dcm4chee2_packages }}"

- name: download dcm4chee
  get_url:
    url: "{{ dcm4chee2_url }}"
    dest: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_archive }}"
    checksum: "{{ dcm4chee2_checksum }}"

- name: unzip dcm4chee
  unarchive:
    src: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_archive }}"
    remote_src: yes
    dest: "{{ dcm4chee2_prefix }}"
    creates: "{{ dcm4chee2_home }}"

- name: download jboss
  get_url:
    url: "{{ dcm4chee2_jboss_url }}"
    dest: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_jboss_archive }}"
    checksum: "{{ dcm4chee2_jboss_checksum }}"

- name: unzip jboss
  unarchive:
    src: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_jboss_archive }}"
    remote_src: yes
    dest: "{{ dcm4chee2_prefix }}"
    creates: "{{ dcm4chee2_jboss_home }}"

- name: copy missing scripts
  copy:
    src: "{{ item }}"
    dest: "{{ dcm4chee2_home }}/bin"
    mode: 0755
  with_items: "{{ dcm4chee2_scripts }}"

- name: install jboss
  command: ./install_jboss.sh "{{ dcm4chee2_jboss_home }}"
  args:
    chdir: "{{ dcm4chee2_home }}/bin"
    creates: "{{ dcm4chee2_home }}/bin/run.jar"
