---
- name: add java repository
  apt_repository:
    repo: "ppa:webupd8team/java"

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# https://coderwall.com/p/zzdapg/ansible-recipe-to-install-java-7-selecting-the-oracle-license
- name: accept oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dcm4chee2_packages }}"

- name: create system group
  group:
    name: "{{ dcm4chee2_system_user }}"
    system: yes
    state: present

- name: create system user
  user:
    name: "{{ dcm4chee2_system_user }}"
    group: "{{ dcm4chee2_system_user }}"
    comment: "DCM4CHEE System User"
    home: "{{ dcm4chee2_home }}"
    createhome: no
    shell: "/usr/sbin/nologin"
    system: yes
    state: present

- name: download dcm4chee
  get_url:
    url: "{{ dcm4chee2_url }}"
    dest: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_archive }}"
    checksum: "{{ dcm4chee2_checksum }}"

- name: unzip dcm4chee
  unarchive:
    src: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_archive }}"
    remote_src: yes
    dest: "{{ dcm4chee2_prefix }}"
    creates: "{{ dcm4chee2_home }}"
  register: unzip_dcm4chee

- name: change ownership of dcm4chee home
  file:
    path: "{{ dcm4chee2_home }}"
    owner: "{{ dcm4chee2_system_user }}"
    group: "{{ dcm4chee2_system_user }}"
    recurse: yes
  when: unzip_dcm4chee.changed

- name: copy missing scripts
  copy:
    src: "{{ item }}"
    dest: "{{ dcm4chee2_home }}/bin"
    owner: "{{ dcm4chee2_system_user }}"
    group: "{{ dcm4chee2_system_user }}"
    mode: 0755
  with_items: "{{ dcm4chee2_scripts }}"

- name: download jboss
  get_url:
    url: "{{ dcm4chee2_jboss_url }}"
    dest: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_jboss_archive }}"
    checksum: "{{ dcm4chee2_jboss_checksum }}"

- name: unzip jboss
  unarchive:
    src: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_jboss_archive }}"
    remote_src: yes
    dest: "{{ dcm4chee2_prefix }}"
    creates: "{{ dcm4chee2_jboss_home }}"

- name: install jboss
  command: ./install_jboss.sh "{{ dcm4chee2_jboss_home }}"
  args:
    chdir: "{{ dcm4chee2_home }}/bin"
    creates: "{{ dcm4chee2_home }}/bin/run.jar"
  become: yes
  become_user: "{{ dcm4chee2_system_user }}"

- name: download arr
  get_url:
    url: "{{ dcm4chee2_arr_url }}"
    dest: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_arr_archive }}"
    checksum: "{{ dcm4chee2_arr_checksum }}"

- name: unzip arr
  unarchive:
    src: "{{ dcm4chee2_prefix }}/{{ dcm4chee2_arr_archive }}"
    remote_src: yes
    dest: "{{ dcm4chee2_prefix }}"
    creates: "{{ dcm4chee2_arr_home }}"
  register: unzip_arr

- name: install arr
  command: "{{ dcm4chee2_home }}/bin/install_arr.sh {{ dcm4chee2_arr_home }}"
  become: yes
  become_user: "{{ dcm4chee2_system_user }}"
  when: unzip_dcm4chee.changed or unzip_arr.changed

- name: copy dcm4chee database config
  template:
    src: pacs-postgres-ds.xml.j2
    dest: "{{ dcm4chee2_home }}/server/default/deploy/pacs-postgres-ds.xml"
    mode: 0640
  become: yes
  become_user: "{{ dcm4chee2_system_user }}"

- name: copy arr database config
  template:
    src: arr-psql-ds.xml.j2
    dest: "{{ dcm4chee2_home }}/server/default/deploy/arr-psql-ds.xml"
    owner: "{{ dcm4chee2_system_user }}"
    group: "{{ dcm4chee2_system_user }}"
    mode: 0640

- name: set java home environment variable
  lineinfile:
    name: /etc/environment
    line: 'JAVA_HOME="{{ dcm4chee2_java_home }}"'
    owner: root
    group: root
    mode: 0644

- name: copy run configuration
  template:
    src: run.conf.j2
    dest: "{{ dcm4chee2_home }}/bin/run.conf"
    owner: "{{ dcm4chee2_system_user }}"
    group: "{{ dcm4chee2_system_user }}"
    mode: 0644
  notify: restart dcm4chee

- name: create symlink to storage
  file:
    path: "{{ dcm4chee2_home }}/server/default/archive"
    src: "{{ dcm4chee2_storage }}"
    state: link
  when: dcm4chee2_storage is defined
