---
# http://www.dcm4che.org/jira/browse/DCMEE-2048
- name: patch postgresql script
  patch:
    src: patch.create.psql
    dest: "{{ dcm4chee2_home }}/sql/create.psql"

- name: create postgresql database
  postgresql_db:
    name: "{{ dcm4chee2_postgresql_database }}"
    state: present
  become: yes
  become_user: "{{ dcm4chee2_postgresql_admin }}"
  register: create_postgresql_database

- name: create postgresql arr database
  postgresql_db:
    name: "{{ dcm4chee2_postgresql_arr_database }}"
    state: present
  become: yes
  become_user: "{{ dcm4chee2_postgresql_admin }}"
  register: create_postgresql_arr_database

- name: create postgresql role
  postgresql_user:
    name: "{{ dcm4chee2_postgresql_user }}"
    password: "{{ dcm4chee2_postgresql_password }}"
    db: "{{ dcm4chee2_postgresql_database }}"
    priv: ALL
    state: present
  become: yes
  become_user: "{{ dcm4chee2_postgresql_admin }}"

- name: initialize postgresql database
  shell: >
    psql -U "{{ dcm4chee2_postgresql_user }}"
    "{{ dcm4chee2_postgresql_database }}" < create.psql
  args:
    chdir: "{{ dcm4chee2_home }}/sql"
  environment:
    PGPASSWORD: '{{ dcm4chee2_postgresql_password }}'
  register: psql_command
  failed_when: psql_command.stderr
  when: create_postgresql_database.changed

- name: initialize postgresql arr database
  shell: >
    psql -U "{{ dcm4chee2_postgresql_user }}"
    "{{ dcm4chee2_postgresql_arr_database }}" <
    "{{ dcm4chee2_arr_home }}/sql/dcm4chee-arr-psql.ddl"
  environment:
    PGPASSWORD: '{{ dcm4chee2_postgresql_password }}'
  register: psql_command
  failed_when: psql_command.stderr
  when: create_postgresql_arr_database.changed
